name = "MLscript"
grammar = "mlscript"
path_suffixes = ["mls"]
line_comments = ["// "]
autoclose_before = ";:.,=}])"
word_characters = ["'"]
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] }
]
